version: 2
updates:
  - package-ecosystem: npm
    directory: /app/ai-ta-app
    schedule:
      interval: weekly
    groups:
      angular:
        patterns:
          - "@angular/*"
    commit-message:
      prefix: "chore(frontend)"

  - package-ecosystem: npm
    directory: /service/ai-ta-api
    schedule:
      interval: weekly
    groups:
      nestjs:
        patterns:
          - "@nestjs/*"
    commit-message:
      prefix: "chore(backend)"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
